# Generated by Django 4.2.2 on 2023-06-17 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carros',
            new_name='Carro',
        ),
    ]
