# Generated by Django 4.2.2 on 2023-06-17 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0003_marca_alter_carro_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='carros/'),
        ),
        migrations.AddField(
            model_name='carro',
            name='placa',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
    ]
