# Generated by Django 4.2.2 on 2023-08-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0005_alter_carro_placa'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarroInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateField(auto_created=True)),
                ('contagem_carros', models.IntegerField()),
                ('carros_valor', models.FloatField()),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
